###

GET http://localhost:3000/user


###

### 
POST http://localhost:3002/user
Content-Type: application/json

{
    "name": "Dorin Cohen3",
    "email": "dorin1@gmail.com",
    "isAdmin":true,
    "password":"12345679",
    "age": "19"
    
}
###

POST http://localhost:3002/auth/register
Content-Type: application/json

{
    "name" :"dorin cohen",
    "email": "dorin7@gmail.com",
    "password":"12345678",
    "age":18
}
###

POST http://localhost:3002/auth/login
Content-Type: application/json

{
    "email": "dorin7@gmail.com",
    "password":"12345678"
    
}



###


