###

GET http://localhost:3000/user

###

GET http://localhost:3000/user?name=Nir

###

GET http://localhost:3000/user/1234567890


###

POST http://localhost:3000/user


###

POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "Dorin Cohen",
    "_id": "1234567892",
    "email": "dorin@gmail.com"
}

