###

GET http://localhost:3000/user

###

GET http://localhost:3000/user?name=Nir

###

GET http://localhost:3000/user/1234567890


###

POST http://localhost:3000/user


###

POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "Dorin Cohen",
    "_id": "1234567892",
    "email": "dorin@gmail.com"
}

### 

GET http://localhost:3000/movie

###

GET http://localhost:3000/movie?movieName=Ilay

###

POST http://localhost:3000/movie

###

POST http://localhost:3000/movie
Content-Type: application/json

{
    "movieName": "Ilay",
    "year": "1998",
    "director": "NirMir",
    "actors": "Dodo",
    "category": "Action",
    "image": "pic",
    "ratingImdb": "9.6",
    "ratingReview": "7.3",

}
